### ISSUE TITLE
library not found for -lUPAPayPlugin

### ISSUE THREAD

**Issue by AwuSnaiper** [lintide/ApplePayDemo#2]
![7efa29a6-3949-4d88-87b6-91e36a776dd3](https://cloud.githubusercontent.com/assets/5173088/13246963/d213a9f8-da51-11e5-946a-23f347b6afca.png)
显示 这个.a文件没找到libUPAPayPlugin.a

**Comment by lintide** [comment]
已修复，谢谢!

**Comment by AwuSnaiper** [comment]
Google一圈才知道这个.a是 银联的包  😄
