### ISSUE TITLE
最后支付返回数据问题

### ISSUE THREAD

**Issue by lilongcnc** [lintide/ApplePayDemo#3]
我完成指纹验证，或者密码通过后，就会进入此函数没有进入这个返回信息的方法中 
- (void)paymentAuthorizationViewController:(PKPaymentAuthorizationViewController *)controller
                     didAuthorizePayment:(PKPayment *)payment
                              completion:(void (^)(PKPaymentAuthorizationStatus status))completion

只进入了
- (void)paymentAuthorizationViewControllerWillAuthorizePayment:(PKPaymentAuthorizationViewController *)controller
  方法里.
  作者你又遇到吗?

**Comment by lintide** [comment]
@lilongcnc  没错，在真机上是回调这个方法。

**Comment by lilongcnc** [comment]
@lintide 那我怎么获取到 服务器返回的相关的payment数据呢?

**Comment by lintide** [comment]
@lilongcnc 在真机上需要跟支付网关进行对接，例如银联。这个 demo 只能在虚拟机上运行。关于银联的对接请参考 [银联 Apple Pay](https://open.unionpay.com/upload/apple/applepay.html)

**Comment by lilongcnc** [comment]
@lintide   作者您好,我先前看的流程是,第一步调用apple pay, 第二步:指纹购买成功后,苹果服务器返回payment等数据  第三步,把payment传给自己公司的服务器解析 第四步,解析出的数据和银联对接.    现在就是想问下第二步payment这个怎么弄得呀?

**Comment by lilongcnc** [comment]
@lintide   冒昧的问一下,您公司接入了apple pay了吗?

**Comment by lintide** [comment]
@lilongcnc 目前还没有。正在申请银联接口。

**Comment by lilongcnc** [comment]
@lintide  好吧,我再看下.

**Comment by lilongcnc** [comment]
@lintide  谢谢您了.

**Comment by lilongcnc** [comment]
@lintide  我看了enjoy 这个app的支付流程,输入错信用卡的支付号的提示是didAuthorizePayment这个方法里提供的,说明真机也应该是进入这个didAuthorizePayment方法中的.您可以看看

**Comment by lintide** [comment]
@lilongcnc 能提供链接吗？

**Comment by lilongcnc** [comment]
@lintide  http://blog.csdn.net/y_fly/article/details/50673427#reply  这是博客地址,最后的评论区.           enjoy直接在appstore搜enjoy即可

**Comment by lintide** [comment]
@lilongcnc 已解决
