### ISSUE TITLE
Profile问题

### ISSUE THREAD

**Issue by lilongcnc** [lintide/ApplePayDemo#4]
楼主,你那个解决bug我还没有试.现在遇到了一个问题,就是在member center上配置好merchant ID 和 对应的app iD之后,创建描述文件之后,直接就是invslid了,或者刚开始显示的activity,但是接着就自动变成了invalid状态了. 这个问题从昨天下午开始就出现了,开始我创建了一次是好的,一直用到了中午,后来打算重新配置一个merchant ID,就再也就不行了,我后来又查了很多资料,感觉创建步骤都没有问题,很困惑,不知道您遇到没有?

**Comment by lintide** [comment]
描述文件为 invalid 状态吗？你点击那个描述文件 -> Edit -> 重新 Generate 试试看。

**Comment by lilongcnc** [comment]
问题已经解决,刚刚我同事在我电脑上按着我说的步骤来了一遍不行,又回到他电脑上来了一遍,就可以了.  然后我自己回到我电脑上操作了一遍也可以了.......这也算解决问题的方法???匪夷所思啊....从昨天下午到上午我弄了一天都没弄好....  您的那个bug我看了确实是好的了!!!

**Comment by lilongcnc** [comment]
@lintide  自己糊涂了貌似."Payment request is invalid: check your entitlements.Connection to remote alert view service failed"之前出现这个问题,我代码里没有改merchant ID

**Comment by zhimeilrc** [comment]
如果 Profile 等有问题，在编译前最好先把 App 删除，并且 Clean 一下，实在不行重启 xCode 也是一个办法。
